### ISSUE TITLE
Readme says LAGPL, lisence says AGPL

### ISSUE THREAD

**Issue by nathanboktae** [moll/node-pg-error#1]
(con't from brianc/node-postgres#700)

Your readme and your actual license file don't match. [Line 5 says AGPL](https://github.com/moll/node-pg-error/blob/master/LICENSE#L5), while the readme says LAGPL.

Why use *GPL anyways? Everything in npm is basically MIT, with BSD, Apache, ISC and other licenses that don't hurt people if they are too lazy to share their modifications.

**Comment by moll** [comment]
Hey,

It's this bit that turns it into Lesser:

> Additional permission under the GNU Affero GPL version 3 section 7:
> If you modify this Program, or any covered work, by linking or
> combining it with other code, such other code is not for that reason
> alone subject to any of the requirements of the GNU Affero GPL version 3.

To save people from legalese, I wrote those 4 bullet points below it. Do you find them in need of clarification?

Why do I use copyleft licenses? I would argue they're more ethical than BSDs/MITs — they're meant to prevent people from leeching, by from taking your code, improving it and not giving back. That's it. I don't particularly find people who don't honor the work I (or any other contributor) have done, and are too lazy to share back, worth catering to.

Does that answer your question?

**Comment by nathanboktae** [comment]
> It's this bit that turns it into Lesser.... I don't particularly find people who don't honor the work I (or any other contributor) have done, and are too lazy to share back, worth catering to.

Supposedly. The thing is with all legal claims, their BS until proven in a court of law. MIT, BSD, Apache have been battle tested. (not to mention MIT is 16 lines) A lot of the LGPL is around using APIs and linking... but when you have JavaScript that only has source, what is that considered? It's JITTed together in the same JavaScript engine with your code... what about minfication? etc... That's why companies have an auto approved policy with these licences, so when using a package, just glancing at it and seeing "oh it's Apache" and not worrying is worth everything.

Moreover, reality is with open source JavaScript these days, there are 10 npm packages that do what you want, people have a lot of choice. When working at a company, all *GPL licenses are often banned. So when someone sees your project with your copyleft license, or the others without, they'll pick the other. And those people will now have users, people filing issues, PRs, etc. Code isn't worth anything these days. People using it and maintaining are worth a lot.

**Comment by moll** [comment]
Well, I'm glad someone else also cares about licensing. 

I concur that declaring a license and enforcing it are separate things. Are you worried the Lesser [Affero GPL](https://en.wikipedia.org/wiki/Affero_General_Public_License) isn't a sound defense when accused of unlawful use of works licensed under it? When I was picking for a license for my open source work, I was specifically looking for a weak copyleft license, one that doesn't force its users to open source their apps, but only require their contributions to the work to be shared. AFAIK, even though IANAL, the Lesser AGPL fits that bill well. Did you bring up JITs and minification to talk about changing JS libraries in running apps? I'm okay with people "statically linking" my works. ;)

If there already were a package that did what everyone wanted, we wouldn't have ended with multiple variations. Some are objectively better, some trade off different things. The price for works that I started, is the requirement to contribute _modifications_ back. Individuals and companies that don't find it a good deal, or are set up with overly simplistic blanket license rejections, are welcome to spend dozens of hours (and thereby thousands of dollars) reimplementing existing works. If you're saying they would contribute back if only the license were free-r, then they're already complying as-is. ;-)

To be honest, I doubt (L)AGPL works, or any other copyleft license for that matter, are missing out that much. [MongoDB](https://en.wikipedia.org/wiki/MongoDB) seems to be doing okay. So is Linux et al.

**Comment by nathanboktae** [comment]
> Did you bring up JITs and minification to talk about changing JS libraries in running apps? I'm okay with people "statically linking" my works. ;)

Doesn't matter what you think. It matters what the courts think.

> MongoDB seems to be doing okay.

Totally different and actually a great counterpoint to your argument. MongoDB is compiled binary executable, and you use a driver to talk to it. In fact, because of issues with AGPL, the [driver uses the Apache license](https://www.mongodb.org/about/licensing/)! 

> So is Linux et al.

I don't ship copies of linux source code minified to browsers all over the world. Again it's totally different, binary vs source.

**Comment by moll** [comment]
Fortunately, given that I own most of the copyright, my stance has to count for something. ;-) As I said before, AGPL + section 7 exclusion seems to match the summarized 4 bullet points. If you're aware of a better weak copyleft license, I'm happy to take a look. 

Are you against the ethics I'm advocating or worried about its implementation? The implementation is derived from the ethics and is easy to change; the ethics are about fairness and reciprocity.

**Comment by nathanboktae** [comment]
The ethics are cute but don't work in the real world is what I'm saying. You'd rather be high and mighty with your ethics than create an open source project easily usable by people. Are you really gonna hunt down and sue people that did do a `git push` back to github of their fork? no.

**Comment by moll** [comment]
Requiring reciprocity doesn't work exactly how? The few companies who'd rather leech than contribute back hardly counts as the majority of the real world. I'm perfectly okay with them spending money rebuilding stuff. It's not like us, copyleft OSS authors, were ever going to see a slice of that money...

I presume you meant hunt down people that _don't_ share their changes? Regardless, whether one will or won't enforce a license through courts doesn't imply one shouldn't license their works with appropriate terms. I'm making a public statement that I don't honor leechers. With the popularity of other P2P, I'm sure no-one's surprised. I'm more surprised there are people _arguing_ for others' work with no intentions of contributing back.

**Comment by nathanboktae** [comment]
It's not no intentions. It's complexity and the legal and corporate reality of writing software these days. You also assume anyone gives a shit about their modifications, which is no one does.

Enjoy the lonely view from your ivory tower. The rest of us are getting stuff done writting software used in the real world.

**Comment by moll** [comment]
If they give no shits about their modifications, then those are precisely the persons I'd rather not help. I'm not a self-sacrificing saint. :smiling_imp: 

Thanks. Remember, us ivory tower people or corps get to use both permissive _and_ weak copyleft licenses. I presume you or your employer only the former. ;-)

**Comment by berezovskyi** [comment]
Please consider EPL/MPL as a friendly copyleft license.

**Comment by moll** [comment]
@berezovskyi:
1. What's EPL/MPL? :)
2. Friendly to whom?

**Comment by berezovskyi** [comment]
https://en.wikipedia.org/wiki/Eclipse_Public_License and https://www.wikiwand.com/en/Mozilla_Public_License require the changes to be contributed back but are friendly to enterprise lawyers because their provisions apply only to the files used/modified so that the proprietary source is not threatened.

PS: By EPL/MPL I meant EPL or MPL.

**Comment by moll** [comment]
Thanks. What exactly is threatening in AGPL with the lesser clause from LGPL? Have you seen a summary that quotes specific statements of the supposedly threatening provisions and describes how Eclipse's and Mozilla's variants "fix" those that you're willing to share? I'm not against getting closer with legalese to the intents I've described in https://github.com/moll/node-pg-error#license, but I find ambiguity in raised worries don't help us get there.

**Comment by berezovskyi** [comment]
Nothing specific. It's just EPL or MPL code is allowed by Eclipse Foundation or Apache Foundation to be used and other licenses require a new license review before any use of them is allowed. It usually takes a few month and might include consultations regarding OSI license approval. As a project lead on a small Eclipse subproject, I would find this to be too high barrier to use your code.

**Comment by moll** [comment]
If you find LGPL and the summary I've outlined in the README reasonable and are truly limited by bureaucracy, why not move your project out of the parent foundation? I fear it's always going to be the case that there are licenses yet to be validated by some organization, but I think LGPL and AGPL have been around long enough to justify their use.

**Comment by berezovskyi** [comment]
Well, I find it reasonable but I prefer lawyers to read licenses. As I expect lawyers not to tell me how to review pull requests. So, I am fairly OK with the idea of lawyers scrutinising the license before letting me use it.

Just to be clear: by adding or deleting a single clause from AGPL you have created a new license. Same as a single line change in the code will result in a new executable. So, the problem is that your code is licensed neither under LGPL nor AGPL.

As you said before, the code is yours in the first place and you decide how to license it. I fully respect that.

--
/Andrew

16 feb. 2019 kl. 14:55 skrev Andri Möll <notifications@github.com<mailto:notifications@github.com>>:


If you find LGPL and the summary I've outlined in the README reasonable and are truly limited by bureaucracy, why not move your project out of the parent foundation? I fear it's always going to be the case that there are licenses yet to be validated by some organization, but I think LGPL and AGPL have been around long enough to justify their use.

**Comment by moll** [comment]
Fair enough on it being a slightly modified license with the "LGPL" clause. If you've got a green light on AGPL-proper, however, then you're welcome to use any of my OSS projects under it, too. The "lesser" clause was meant to limit the the scope of AGPL, but if that's not a concern, more copyleft is hardly worse. :)

**Comment by no-identd** [comment]
Y'all might want to read this:

http://mo.morsi.org/blog/2009/08/13/lesser_affero_gplv3/

**Comment by moll** [comment]
^ That's the article that led me to the "Lesser" AGPL back then in fact. :)
