### ISSUE TITLE
working with connection pool

### ISSUE THREAD

**Issue by vitaly-t** [moll/node-pg-error#2]
The recommended way for using `node-postgres` today is via the connection pool, which means we do not have access to the Client/Connection objects directly.

How can we use this library through the connection pool?

**Comment by moll** [comment]
Hey. I'm not sure as I haven't used that particular pool, but pools usually have a function or event to modify newly created instances of objects. Running code on new instances is occasionally necessary for setting PostgreSQL options such as various return formats. You could then also hook up PgError.

**Comment by vitaly-t** [comment]
> I'm not sure as I haven't used that particular pool

That's the only pool used by node-postgres :)

> pools usually have a function or event to modify newly created instances of objects

It would be nice to know if this is possible with that generic-pool library :)

**Comment by moll** [comment]
I've used Pg with Knex primarily. I'm not even sure which pooling thing it uses, but it does have a function/event for new instances I described above.

Would you mind checking in node-postgres' docs to see how to centrally get access to new instances and letting us all know, too? :)

**Comment by pelicanorojo** [comment]
Hi to everyone,

(Based on sample with pool on https://www.npmjs.com/package/pg)
Outside the callback:
`pool.connect(function(err, client, done) {....`

I've defined:

```
function pgErrorEmition(err) {
  switch (err.severity) {
    case "ERROR":
    case "FATAL":
    case "PANIC": return this.emit("error", err)
    default: return this.emit("notice", err)
  }
};
```

And inside:

```
client.connection.parseE = PgError.parse;
client.connection.parseN = PgError.parse;
client.connection.on("PgError", pgErrorEmition);
```

Actually, I've done some promisification, and a chainable query object, soon in my repo.

Have a good day!

**Comment by moll** [comment]
Thanks for the story, @pelicanorojo.

On a related note, I'll close this issue as there's nothing _actionable_ right now to do with it. If there is, we can open it any time. ;)

**Comment by ap32** [comment]
```
function pgErrorEmition(err) {
  switch (err.severity) {
    case "ERROR":
    case "FATAL":
    case "PANIC":
      return this.emit("error", err);
    default:
      return this.emit("notice", err);
  }
}

pool.on('connect', client => {
  client.connection.on("PgError", pgErrorEmition);
});
```
